// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/horse/models.proto

package horsepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HorseGender struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HorseGender) Reset() {
	*x = HorseGender{}
	mi := &file_api_horse_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HorseGender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HorseGender) ProtoMessage() {}

func (x *HorseGender) ProtoReflect() protoreflect.Message {
	mi := &file_api_horse_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HorseGender.ProtoReflect.Descriptor instead.
func (*HorseGender) Descriptor() ([]byte, []int) {
	return file_api_horse_models_proto_rawDescGZIP(), []int{0}
}

func (x *HorseGender) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HorseGender) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HorseGender) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type HorseColor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HorseColor) Reset() {
	*x = HorseColor{}
	mi := &file_api_horse_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HorseColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HorseColor) ProtoMessage() {}

func (x *HorseColor) ProtoReflect() protoreflect.Message {
	mi := &file_api_horse_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HorseColor.ProtoReflect.Descriptor instead.
func (*HorseColor) Descriptor() ([]byte, []int) {
	return file_api_horse_models_proto_rawDescGZIP(), []int{1}
}

func (x *HorseColor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HorseColor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HorseColor) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type HorseBirthplace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HorseBirthplace) Reset() {
	*x = HorseBirthplace{}
	mi := &file_api_horse_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HorseBirthplace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HorseBirthplace) ProtoMessage() {}

func (x *HorseBirthplace) ProtoReflect() protoreflect.Message {
	mi := &file_api_horse_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HorseBirthplace.ProtoReflect.Descriptor instead.
func (*HorseBirthplace) Descriptor() ([]byte, []int) {
	return file_api_horse_models_proto_rawDescGZIP(), []int{2}
}

func (x *HorseBirthplace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HorseBirthplace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HorseBirthplace) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type HorseGeneticMarker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HorseGeneticMarker) Reset() {
	*x = HorseGeneticMarker{}
	mi := &file_api_horse_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HorseGeneticMarker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HorseGeneticMarker) ProtoMessage() {}

func (x *HorseGeneticMarker) ProtoReflect() protoreflect.Message {
	mi := &file_api_horse_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HorseGeneticMarker.ProtoReflect.Descriptor instead.
func (*HorseGeneticMarker) Descriptor() ([]byte, []int) {
	return file_api_horse_models_proto_rawDescGZIP(), []int{3}
}

func (x *HorseGeneticMarker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HorseGeneticMarker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HorseGeneticMarker) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

var File_api_horse_models_proto protoreflect.FileDescriptor

const file_api_horse_models_proto_rawDesc = "" +
	"\n" +
	"\x16api/horse/models.proto\x12\x06models\"h\n" +
	"\vHorseGender\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"g\n" +
	"\n" +
	"HorseColor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"l\n" +
	"\x0fHorseBirthplace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"o\n" +
	"\x12HorseGeneticMarker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\x13Z\x11api/horse;horsepbb\x06proto3"

var (
	file_api_horse_models_proto_rawDescOnce sync.Once
	file_api_horse_models_proto_rawDescData []byte
)

func file_api_horse_models_proto_rawDescGZIP() []byte {
	file_api_horse_models_proto_rawDescOnce.Do(func() {
		file_api_horse_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_horse_models_proto_rawDesc), len(file_api_horse_models_proto_rawDesc)))
	})
	return file_api_horse_models_proto_rawDescData
}

var file_api_horse_models_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_horse_models_proto_goTypes = []any{
	(*HorseGender)(nil),        // 0: models.HorseGender
	(*HorseColor)(nil),         // 1: models.HorseColor
	(*HorseBirthplace)(nil),    // 2: models.HorseBirthplace
	(*HorseGeneticMarker)(nil), // 3: models.HorseGeneticMarker
}
var file_api_horse_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_horse_models_proto_init() }
func file_api_horse_models_proto_init() {
	if File_api_horse_models_proto != nil {
		return
	}
	file_api_horse_models_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_horse_models_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_horse_models_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_horse_models_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_horse_models_proto_rawDesc), len(file_api_horse_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_horse_models_proto_goTypes,
		DependencyIndexes: file_api_horse_models_proto_depIdxs,
		MessageInfos:      file_api_horse_models_proto_msgTypes,
	}.Build()
	File_api_horse_models_proto = out.File
	file_api_horse_models_proto_goTypes = nil
	file_api_horse_models_proto_depIdxs = nil
}
