// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: api/horse/service.proto

package horsepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HorseService_CreateGender_FullMethodName = "/horse.HorseService/CreateGender"
)

// HorseServiceClient is the client API for HorseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HorseServiceClient interface {
	CreateGender(ctx context.Context, in *CreateGenderRequest, opts ...grpc.CallOption) (*CreateGenderResponse, error)
}

type horseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHorseServiceClient(cc grpc.ClientConnInterface) HorseServiceClient {
	return &horseServiceClient{cc}
}

func (c *horseServiceClient) CreateGender(ctx context.Context, in *CreateGenderRequest, opts ...grpc.CallOption) (*CreateGenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGenderResponse)
	err := c.cc.Invoke(ctx, HorseService_CreateGender_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HorseServiceServer is the server API for HorseService service.
// All implementations must embed UnimplementedHorseServiceServer
// for forward compatibility.
type HorseServiceServer interface {
	CreateGender(context.Context, *CreateGenderRequest) (*CreateGenderResponse, error)
	mustEmbedUnimplementedHorseServiceServer()
}

// UnimplementedHorseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHorseServiceServer struct{}

func (UnimplementedHorseServiceServer) CreateGender(context.Context, *CreateGenderRequest) (*CreateGenderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGender not implemented")
}
func (UnimplementedHorseServiceServer) mustEmbedUnimplementedHorseServiceServer() {}
func (UnimplementedHorseServiceServer) testEmbeddedByValue()                      {}

// UnsafeHorseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HorseServiceServer will
// result in compilation errors.
type UnsafeHorseServiceServer interface {
	mustEmbedUnimplementedHorseServiceServer()
}

func RegisterHorseServiceServer(s grpc.ServiceRegistrar, srv HorseServiceServer) {
	// If the following call pancis, it indicates UnimplementedHorseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HorseService_ServiceDesc, srv)
}

func _HorseService_CreateGender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HorseServiceServer).CreateGender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HorseService_CreateGender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HorseServiceServer).CreateGender(ctx, req.(*CreateGenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HorseService_ServiceDesc is the grpc.ServiceDesc for HorseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HorseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "horse.HorseService",
	HandlerType: (*HorseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGender",
			Handler:    _HorseService_CreateGender_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/horse/service.proto",
}
