// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/horse/service.proto

package horsepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGenderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGenderRequest) Reset() {
	*x = CreateGenderRequest{}
	mi := &file_api_horse_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenderRequest) ProtoMessage() {}

func (x *CreateGenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_horse_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGenderRequest.ProtoReflect.Descriptor instead.
func (*CreateGenderRequest) Descriptor() ([]byte, []int) {
	return file_api_horse_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGenderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGenderRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateGenderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGenderResponse) Reset() {
	*x = CreateGenderResponse{}
	mi := &file_api_horse_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenderResponse) ProtoMessage() {}

func (x *CreateGenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_horse_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGenderResponse.ProtoReflect.Descriptor instead.
func (*CreateGenderResponse) Descriptor() ([]byte, []int) {
	return file_api_horse_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGenderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateGenderResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGenderResponse) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

var File_api_horse_service_proto protoreflect.FileDescriptor

const file_api_horse_service_proto_rawDesc = "" +
	"\n" +
	"\x17api/horse/service.proto\x12\x05horse\"`\n" +
	"\x13CreateGenderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"q\n" +
	"\x14CreateGenderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description2W\n" +
	"\fHorseService\x12G\n" +
	"\fCreateGender\x12\x1a.horse.CreateGenderRequest\x1a\x1b.horse.CreateGenderResponseB\x13Z\x11api/horse;horsepbb\x06proto3"

var (
	file_api_horse_service_proto_rawDescOnce sync.Once
	file_api_horse_service_proto_rawDescData []byte
)

func file_api_horse_service_proto_rawDescGZIP() []byte {
	file_api_horse_service_proto_rawDescOnce.Do(func() {
		file_api_horse_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_horse_service_proto_rawDesc), len(file_api_horse_service_proto_rawDesc)))
	})
	return file_api_horse_service_proto_rawDescData
}

var file_api_horse_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_horse_service_proto_goTypes = []any{
	(*CreateGenderRequest)(nil),  // 0: horse.CreateGenderRequest
	(*CreateGenderResponse)(nil), // 1: horse.CreateGenderResponse
}
var file_api_horse_service_proto_depIdxs = []int32{
	0, // 0: horse.HorseService.CreateGender:input_type -> horse.CreateGenderRequest
	1, // 1: horse.HorseService.CreateGender:output_type -> horse.CreateGenderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_horse_service_proto_init() }
func file_api_horse_service_proto_init() {
	if File_api_horse_service_proto != nil {
		return
	}
	file_api_horse_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_horse_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_horse_service_proto_rawDesc), len(file_api_horse_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_horse_service_proto_goTypes,
		DependencyIndexes: file_api_horse_service_proto_depIdxs,
		MessageInfos:      file_api_horse_service_proto_msgTypes,
	}.Build()
	File_api_horse_service_proto = out.File
	file_api_horse_service_proto_goTypes = nil
	file_api_horse_service_proto_depIdxs = nil
}
