// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/horse/service.proto

package horsepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGenderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGenderRequest) Reset() {
	*x = CreateGenderRequest{}
	mi := &file_api_horse_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenderRequest) ProtoMessage() {}

func (x *CreateGenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_horse_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGenderRequest.ProtoReflect.Descriptor instead.
func (*CreateGenderRequest) Descriptor() ([]byte, []int) {
	return file_api_horse_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGenderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGenderRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateGenderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HorseGender   *HorseGender           `protobuf:"bytes,1,opt,name=horse_gender,json=horseGender,proto3" json:"horse_gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGenderResponse) Reset() {
	*x = CreateGenderResponse{}
	mi := &file_api_horse_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenderResponse) ProtoMessage() {}

func (x *CreateGenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_horse_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGenderResponse.ProtoReflect.Descriptor instead.
func (*CreateGenderResponse) Descriptor() ([]byte, []int) {
	return file_api_horse_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGenderResponse) GetHorseGender() *HorseGender {
	if x != nil {
		return x.HorseGender
	}
	return nil
}

type GetGenderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genders       []*HorseGender         `protobuf:"bytes,1,rep,name=genders,proto3" json:"genders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenderListResponse) Reset() {
	*x = GetGenderListResponse{}
	mi := &file_api_horse_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenderListResponse) ProtoMessage() {}

func (x *GetGenderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_horse_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenderListResponse.ProtoReflect.Descriptor instead.
func (*GetGenderListResponse) Descriptor() ([]byte, []int) {
	return file_api_horse_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetGenderListResponse) GetGenders() []*HorseGender {
	if x != nil {
		return x.Genders
	}
	return nil
}

type GetColorListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Colors        []*HorseColor          `protobuf:"bytes,1,rep,name=colors,proto3" json:"colors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetColorListResponse) Reset() {
	*x = GetColorListResponse{}
	mi := &file_api_horse_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetColorListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColorListResponse) ProtoMessage() {}

func (x *GetColorListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_horse_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColorListResponse.ProtoReflect.Descriptor instead.
func (*GetColorListResponse) Descriptor() ([]byte, []int) {
	return file_api_horse_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetColorListResponse) GetColors() []*HorseColor {
	if x != nil {
		return x.Colors
	}
	return nil
}

type GetBirthplaceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Birthplaces   []*HorseBirthplace     `protobuf:"bytes,1,rep,name=birthplaces,proto3" json:"birthplaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBirthplaceListResponse) Reset() {
	*x = GetBirthplaceListResponse{}
	mi := &file_api_horse_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBirthplaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirthplaceListResponse) ProtoMessage() {}

func (x *GetBirthplaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_horse_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirthplaceListResponse.ProtoReflect.Descriptor instead.
func (*GetBirthplaceListResponse) Descriptor() ([]byte, []int) {
	return file_api_horse_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetBirthplaceListResponse) GetBirthplaces() []*HorseBirthplace {
	if x != nil {
		return x.Birthplaces
	}
	return nil
}

type GetGeneticMarkerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markers       []*HorseGeneticMarker  `protobuf:"bytes,1,rep,name=markers,proto3" json:"markers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGeneticMarkerListResponse) Reset() {
	*x = GetGeneticMarkerListResponse{}
	mi := &file_api_horse_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeneticMarkerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeneticMarkerListResponse) ProtoMessage() {}

func (x *GetGeneticMarkerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_horse_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeneticMarkerListResponse.ProtoReflect.Descriptor instead.
func (*GetGeneticMarkerListResponse) Descriptor() ([]byte, []int) {
	return file_api_horse_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetGeneticMarkerListResponse) GetMarkers() []*HorseGeneticMarker {
	if x != nil {
		return x.Markers
	}
	return nil
}

var File_api_horse_service_proto protoreflect.FileDescriptor

const file_api_horse_service_proto_rawDesc = "" +
	"\n" +
	"\x17api/horse/service.proto\x12\x05horse\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16api/horse/models.proto\"`\n" +
	"\x13CreateGenderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"N\n" +
	"\x14CreateGenderResponse\x126\n" +
	"\fhorse_gender\x18\x01 \x01(\v2\x13.models.HorseGenderR\vhorseGender\"F\n" +
	"\x15GetGenderListResponse\x12-\n" +
	"\agenders\x18\x01 \x03(\v2\x13.models.HorseGenderR\agenders\"B\n" +
	"\x14GetColorListResponse\x12*\n" +
	"\x06colors\x18\x01 \x03(\v2\x12.models.HorseColorR\x06colors\"V\n" +
	"\x19GetBirthplaceListResponse\x129\n" +
	"\vbirthplaces\x18\x01 \x03(\v2\x17.models.HorseBirthplaceR\vbirthplaces\"T\n" +
	"\x1cGetGeneticMarkerListResponse\x124\n" +
	"\amarkers\x18\x01 \x03(\v2\x1a.models.HorseGeneticMarkerR\amarkers2\x87\x03\n" +
	"\fHorseService\x12G\n" +
	"\fCreateGender\x12\x1a.horse.CreateGenderRequest\x1a\x1b.horse.CreateGenderResponse\x12E\n" +
	"\rGetGenderList\x12\x16.google.protobuf.Empty\x1a\x1c.horse.GetGenderListResponse\x12C\n" +
	"\fGetColorList\x12\x16.google.protobuf.Empty\x1a\x1b.horse.GetColorListResponse\x12M\n" +
	"\x11GetBirthplaceList\x12\x16.google.protobuf.Empty\x1a .horse.GetBirthplaceListResponse\x12S\n" +
	"\x14GetGeneticMarkerList\x12\x16.google.protobuf.Empty\x1a#.horse.GetGeneticMarkerListResponseB\x13Z\x11api/horse;horsepbb\x06proto3"

var (
	file_api_horse_service_proto_rawDescOnce sync.Once
	file_api_horse_service_proto_rawDescData []byte
)

func file_api_horse_service_proto_rawDescGZIP() []byte {
	file_api_horse_service_proto_rawDescOnce.Do(func() {
		file_api_horse_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_horse_service_proto_rawDesc), len(file_api_horse_service_proto_rawDesc)))
	})
	return file_api_horse_service_proto_rawDescData
}

var file_api_horse_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_horse_service_proto_goTypes = []any{
	(*CreateGenderRequest)(nil),          // 0: horse.CreateGenderRequest
	(*CreateGenderResponse)(nil),         // 1: horse.CreateGenderResponse
	(*GetGenderListResponse)(nil),        // 2: horse.GetGenderListResponse
	(*GetColorListResponse)(nil),         // 3: horse.GetColorListResponse
	(*GetBirthplaceListResponse)(nil),    // 4: horse.GetBirthplaceListResponse
	(*GetGeneticMarkerListResponse)(nil), // 5: horse.GetGeneticMarkerListResponse
	(*HorseGender)(nil),                  // 6: models.HorseGender
	(*HorseColor)(nil),                   // 7: models.HorseColor
	(*HorseBirthplace)(nil),              // 8: models.HorseBirthplace
	(*HorseGeneticMarker)(nil),           // 9: models.HorseGeneticMarker
	(*emptypb.Empty)(nil),                // 10: google.protobuf.Empty
}
var file_api_horse_service_proto_depIdxs = []int32{
	6,  // 0: horse.CreateGenderResponse.horse_gender:type_name -> models.HorseGender
	6,  // 1: horse.GetGenderListResponse.genders:type_name -> models.HorseGender
	7,  // 2: horse.GetColorListResponse.colors:type_name -> models.HorseColor
	8,  // 3: horse.GetBirthplaceListResponse.birthplaces:type_name -> models.HorseBirthplace
	9,  // 4: horse.GetGeneticMarkerListResponse.markers:type_name -> models.HorseGeneticMarker
	0,  // 5: horse.HorseService.CreateGender:input_type -> horse.CreateGenderRequest
	10, // 6: horse.HorseService.GetGenderList:input_type -> google.protobuf.Empty
	10, // 7: horse.HorseService.GetColorList:input_type -> google.protobuf.Empty
	10, // 8: horse.HorseService.GetBirthplaceList:input_type -> google.protobuf.Empty
	10, // 9: horse.HorseService.GetGeneticMarkerList:input_type -> google.protobuf.Empty
	1,  // 10: horse.HorseService.CreateGender:output_type -> horse.CreateGenderResponse
	2,  // 11: horse.HorseService.GetGenderList:output_type -> horse.GetGenderListResponse
	3,  // 12: horse.HorseService.GetColorList:output_type -> horse.GetColorListResponse
	4,  // 13: horse.HorseService.GetBirthplaceList:output_type -> horse.GetBirthplaceListResponse
	5,  // 14: horse.HorseService.GetGeneticMarkerList:output_type -> horse.GetGeneticMarkerListResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_horse_service_proto_init() }
func file_api_horse_service_proto_init() {
	if File_api_horse_service_proto != nil {
		return
	}
	file_api_horse_models_proto_init()
	file_api_horse_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_horse_service_proto_rawDesc), len(file_api_horse_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_horse_service_proto_goTypes,
		DependencyIndexes: file_api_horse_service_proto_depIdxs,
		MessageInfos:      file_api_horse_service_proto_msgTypes,
	}.Build()
	File_api_horse_service_proto = out.File
	file_api_horse_service_proto_goTypes = nil
	file_api_horse_service_proto_depIdxs = nil
}
