// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Справочник генетических маркеров
type GeneticMarker struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
}

// Основная таблица с информацией о лошадях
type Horse struct {
	// Уникальный идентификатор лошади
	ID pgtype.UUID
	// Идентификатор табуна, к которому принадлежит лошадь
	Herd pgtype.UUID
	// Пол лошади
	Gender pgtype.UUID
	// Имя лошади
	Name pgtype.Text
	// День рождения лошади
	BirthDay pgtype.Int4
	// Месяц рождения лошади
	BirthMonth pgtype.Int4
	// Год рождения лошади
	BirthYear pgtype.Int4
	// Место рождения лошади
	BirthPlace pgtype.UUID
	// Высота в холке (в сантиметрах)
	WithersHeight pgtype.Int4
	// Идентификатор отца (жеребца)
	Sire pgtype.UUID
	// Идентификатор матери (кобылы)
	Dam pgtype.UUID
	// Статус беременности (true, если беременна)
	IsPregnant pgtype.Bool
	// Статус лошади (true, если мертва)
	IsDead pgtype.Bool
	// Время создания записи
	CreatedAt pgtype.Timestamp
	// Время последнего обновления записи
	UpdatedAt pgtype.Timestamp
	// Описание лошади
	Description pgtype.Text
}

// Справочник мест рождения лошадей
type HorseBirthplace struct {
	ID pgtype.UUID
	// Название места рождения
	Name        string
	Description pgtype.Text
}

// Справочник пород лошадей
type HorseBreed struct {
	ID pgtype.UUID
	// Название породы
	Name        string
	Description pgtype.Text
}

// Таблица для хранения породной принадлежности лошадей с указанием процента
type HorseBreedLink struct {
	// Уникальный идентификатор записи
	ID pgtype.UUID
	// Идентификатор лошади
	Horse pgtype.UUID
	// Идентификатор породы
	Breed pgtype.UUID
	// Процент принадлежности к породе, целое число от 0 до 10000, где 10000 = 100%
	Percent int32
}

// Справочник окрасов лошадей
type HorseColor struct {
	ID pgtype.UUID
	// Название окраса лошади
	Name        string
	Description pgtype.Text
}

// Таблица для хранения окрасов лошадей
type HorseColorLink struct {
	// Уникальный идентификатор записи
	ID pgtype.UUID
	// Идентификатор лошади
	Horse pgtype.UUID
	// Идентификатор окраса
	Color pgtype.UUID
}

// Справочник полов лошадей
type HorseGender struct {
	ID pgtype.UUID
	// Название пола лошади
	Name        string
	Description pgtype.Text
}

// Таблица для хранения генетических маркеров лошадей
type HorseGeneticMarker struct {
	// Уникальный идентификатор записи
	ID pgtype.UUID
	// Идентификатор лошади
	Horse pgtype.UUID
	// Идентификатор генетического маркера
	Marker pgtype.UUID
}
